
info:
  version: 1.0.0
  title: api de productos
servers:
  - url: http://localhost:3000
paths:
  /:
    post:
      summary: Crea un nuevo producto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
      responses:
        '200':
          description: Producto creado con éxito
    get:
      summary: Obtiene una lista de productos
      parameters:
        - in: query
          name: limit
          schema:
            type: number
          description: Límite de productos para mostrar
        - in: query
          name: page1
          schema:
            type: number
          description: Número de página
        - in: query
          name: sort
          schema:
            type: string
          description: Ordenar productos
        - in: query
          name: query
          schema:
            type: string
          description: Query para buscar productos
      responses:
        '200':
          description: Lista de productos obtenida con éxito
        '500':
          description: Error interno del servidor
  /insertar:
    post:
      summary: Inserta un nuevo producto (pendiente de implementación)
      responses:
        '200':
          description: Producto insertado con éxito (pendiente de implementación)
